# Change baseurl before deploy
baseurl = "https://aiar.site/"
languageCode = "en-us"
paginate = 5
title = "Aiar's Site"


# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

# Change it to your Disqus shortname before using
disqusShortname = "Aiar"

# Custom
[params]
favicon = '/favicon.ico'
